import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { useState } from 'react';
import Button from '$/components/Button';
import ErrorBox from '$/components/ErrorBox';
import { InfoBanner } from '$/components/InfoBanner';
import Loading from '$/components/Loading';
import MainLayout from '$/components/MainLayout';
import Modal from '$/components/Modal';
import Tag from '$/components/Tag';
import { useToast } from '$/components/ToastContext';
import AddTagModal from '$/modals/AddTagModal';
import './TagsAndMetadata.css';
import { CountedTag } from '$/types/tag';

export default function TagsAndMetadata() {
	const { showToast } = useToast();

	const tagsQuery = useQuery({
		queryKey: ['tags'],
		queryFn: async () => {
			const res = await axios.get('/api/tags');
			return await CountedTag.array().parseAsync(res.data);
		},
	});

	const [addTagOpen, setAddTagOpen] = useState(false);
	const [activeModal, setActiveModal] = useState<'edit' | 'delete' | null>(
		null,
	);
	const [selectedTag, setSelectedTag] = useState<CountedTag | null>(null);

	const openEdit = (tag: CountedTag) => {
		setSelectedTag(tag);
		setActiveModal('edit');
	};

	const openDelete = (tag: CountedTag) => {
		setSelectedTag(tag);
		setActiveModal('delete');
	};

	const closeModal = () => {
		setActiveModal(null);
		setSelectedTag(null);
	};

	const handleDelete = () => {
		if (!selectedTag) return;

		// TODO: call DELETE /api/tags/:name and invalidate ['tags']
		showToast('Tag deleted', 'success');
		closeModal();
	};

	if (tagsQuery.isError) {
		return (
			<MainLayout title="Tags & Metadata">
				<ErrorBox message="Failed to load tags. Refresh the page and try again." />
			</MainLayout>
		);
	}

	if (tagsQuery.isPending) {
		return (
			<MainLayout title="Tags & Metadata">
				<Loading vertical />
			</MainLayout>
		);
	}

	return (
		<MainLayout title="Tags & Metadata">
			<div className="TagsAndMetadata-header">
				<button
					key={'addtag'}
					className="Header-addTag u-button"
					type="button"
					onClick={() => setAddTagOpen(true)}
				>
					+ Add Tag
				</button>
			</div>

			<div className="tag-card">
				<InfoBanner message="AI Tags are auto-generated by AI at import time and weighted by relevance. You can also manually add, edit, or remove tags." />

				{/* Table */}
				<div className="UserManagement-tableWrap">
					<table className="UserManagement-users">
						<thead className="Users-thead">
							<tr>
								<th>Tag</th>
								<th>Sermons</th>
								<th>Relevance Weight</th>
								<th>Source</th>
								<th>Actions</th>
							</tr>
						</thead>

						<tbody>
							{tagsQuery.data.map(tag => (
								<tr key={tag.name}>
									<td>
										<Tag variant="green">{tag.name}</Tag>
									</td>

									<td>{tag.count}</td>

									<td>—</td>

									<td>
										<Tag variant={tag.source === 'ai' ? 'blue' : 'outline'}>
											{tag.source === 'ai' ? 'AI' : 'Manual'}
										</Tag>
									</td>

									<td className="Users-actions">
										<button
											type="button"
											className="Users-actionEdit u-button"
											onClick={() => openEdit(tag)}
										>
											Edit
										</button>

										<button
											type="button"
											className="Users-actionRemove u-button"
											onClick={() => openDelete(tag)}
										>
											Delete
										</button>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>

				{/* Delete Modal */}
				{activeModal === 'delete' && selectedTag && (
					<Modal isOpen onClose={closeModal} title="Delete Tag">
						<p>Are you sure you want to delete "{selectedTag.name}"?</p>

						<div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
							<Button variant="secondary" onClick={closeModal}>
								Cancel
							</Button>
							<Button variant="primary" onClick={handleDelete}>
								Delete
							</Button>
						</div>
					</Modal>
				)}
			</div>

			<AddTagModal isOpen={addTagOpen} onClose={() => setAddTagOpen(false)} />
		</MainLayout>
	);
}
