"""video_link to text

Revision ID: 121572e8cf72
Revises: b2f09d55781a
Create Date: 2026-09-30 17:54:15.459821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121572e8cf72'
down_revision = 'b2f09d55781a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.alter_column('video_link',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.alter_column('video_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
