"""sermon storage and processing fields

Revision ID: 42c65e30fe27
Revises: 121572e8cf72
Create Date: 2026-09-30 19:08:00.678902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c65e30fe27'
down_revision = '121572e8cf72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('audio_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.drop_column('processed_at')
        batch_op.drop_column('processing_error')
        batch_op.drop_column('audio_key')
        batch_op.drop_column('storage_key')

    # ### end Alembic commands ###
