"""youtube ids and wider titles

Revision ID: 9ec1bf424e99
Revises: 42c65e30fe27
Create Date: 2026-10-05 16:05:51.486577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec1bf424e99'
down_revision = '42c65e30fe27'
branch_labels = None
depends_on = None


def upgrade():
    # Unique constraints are named by hand, since autogenerate leaves them unnamed and the downgrade could not drop them.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_playlist_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_series_youtube_playlist_id', ['youtube_playlist_id'])

    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_video_id', sa.String(length=16), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_sermon_youtube_video_id', ['youtube_video_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sermon_youtube_video_id', type_='unique')
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('youtube_video_id')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_constraint('uq_series_youtube_playlist_id', type_='unique')
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('youtube_playlist_id')

    # ### end Alembic commands ###
