"""baseline

Revision ID: b2f09d55781a
Revises: 
Create Date: 2026-09-30 17:46:10.897246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f09d55781a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('AI', 'MANUAL', name='tagsource', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sermon',
    sa.Column('id', sa.Integer(), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('video_link', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'PUBLISHED', 'FAILED', name='uploadstatus', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sermon_Tag',
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermon.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sermon_id', 'tag_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sermon_Tag')
    op.drop_table('sermon')
    op.drop_table('tag')
    op.drop_table('speaker')
    op.drop_table('series')
    # ### end Alembic commands ###
