import { useState } from 'react';
import Button from '$/components/Button';
import Modal from '$/components/Modal';
import Tag from '$/components/Tag';
import { useToast } from '$/components/ToastContext';
import './Tags.css';

type TagType = {
	id: string;
	name: string;
	sermons: number;
	weight: number;
	source: 'AI' | 'Manual';
};

const initialTags: TagType[] = [
	{ id: '1', name: 'faith', sermons: 342, weight: 80, source: 'AI' },
	{ id: '2', name: 'hope', sermons: 289, weight: 75, source: 'AI' },
	{ id: '3', name: 'grace', sermons: 276, weight: 70, source: 'AI' },
	{ id: '4', name: 'healing', sermons: 198, weight: 60, source: 'AI' },
	{ id: '5', name: 'anxeity', sermons: 156, weight: 50, source: 'Manual' },
];

export default function Table() {
	const { showToast } = useToast();

	const [tags, setTags] = useState<TagType[]>(initialTags);
	const [activeModal, setActiveModal] = useState<'edit' | 'delete' | null>(
		null,
	);
	const [selectedTag, setSelectedTag] = useState<TagType | null>(null);

	const openEdit = (tag: TagType) => {
		setSelectedTag(tag);
		setActiveModal('edit');
	};

	const openDelete = (tag: TagType) => {
		setSelectedTag(tag);
		setActiveModal('delete');
	};

	const closeModal = () => {
		setActiveModal(null);
		setSelectedTag(null);
	};

	const handleDelete = () => {
		if (!selectedTag) return;

		setTags(prev => prev.filter(t => t.id !== selectedTag.id));
		showToast('Tag deleted', 'success');
		closeModal();
	};

	return (
		<div className="tag-card">
			{/* Header */}
			<div className="tag-header">
				<div>
					<p className="tag-header-info">
						AI Tags are auto-generated by AI at import time and weighted by
						relevance. You can also manually add, edit, or remove tags.
					</p>
				</div>
			</div>

			{/* Table */}
			<div className="UserManagement-tableWrap">
				<table className="UserManagement-users">
					<thead className="Users-thead">
						<tr>
							<th>Tag</th>
							<th>Sermons</th>
							<th>Relevance Weight</th>
							<th>Source</th>
							<th>Actions</th>
						</tr>
					</thead>

					<tbody>
						{tags.map(tag => (
							<tr key={tag.id}>
								<td>
									<Tag variant="outline">{tag.name}</Tag>
								</td>

								<td>{tag.sermons}</td>

								<td>
									<progress max={100} value={tag.weight} />
								</td>

								<td>
									<Tag variant={tag.source === 'AI' ? 'blue' : 'outline'}>
										{tag.source}
									</Tag>
								</td>

								<td className="Users-actions">
									<button
										type="button"
										className="Users-actionEdit u-button"
										onClick={() => openEdit(tag)}
									>
										Edit
									</button>

									<button
										type="button"
										className="Users-actionRemove u-button"
										onClick={() => openDelete(tag)}
									>
										Delete
									</button>
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</div>

			{/* Delete Modal */}
			{activeModal === 'delete' && selectedTag && (
				<Modal isOpen onClose={closeModal} title="Delete Tag">
					<p>Are you sure you want to delete "{selectedTag.name}"?</p>

					<div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
						<Button variant="secondary" onClick={closeModal}>
							Cancel
						</Button>
						<Button variant="primary" onClick={handleDelete}>
							Delete
						</Button>
					</div>
				</Modal>
			)}
		</div>
	);
}
