name: Frontend Checks
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  NODE_VERSION: 24

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: Frontend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Frontend
          path: Frontend

  vite:
    name: Run Vitest tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: Frontend

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest tests
        run: npm run test

  playwright:
    name: Run Playwright tests
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: Frontend

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run e2e

      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  biome:
    name: Run Biome checks
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: Frontend

      - name: Install dependencies
        run: npm ci

      - name: Create blank .gitignore
        run: touch .gitignore

      - name: Run Biome
        run: npx biome ci
